#!/bin/bash
### BEGIN INIT INFO
# Provides:          iptable-rules
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Should-Start:      iptables
# Should-Stop:       iptables
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Adds iptables rules on boot.
# Description:       Adds iptables rules on boot.
### END INIT INFO

sudo /sbin/iptables --flush 

sudo /sbin/iptables -A INPUT -p tcp -m multiport --destination-port 25,587 -j DROP
sudo /sbin/iptables -A INPUT -p tcp -m multiport --destination-port 1199,5000,50050 -s phone_public_ip,Phone_private_ip,127.0.0.1 -j ACCEPT
sudo /sbin/iptables -A INPUT -p tcp -m multiport --destination-port 1199,5000,50050 -j DROP
sudo /sbin/iptables -A OUTPUT -p tcp --dport 993 -d localhost -m owner ! --uid-owner root -j REJECT
sudo /sbin/iptables -t filter -I INPUT -p tcp --syn --dport 1199 -m connlimit --connlimit-above 3 --connlimit-mask 32 -j DROP
